src/Entity/School.php
<?php

namespace App\Entity;

use App\Repository\SchoolRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SchoolRepository::class)]
class School
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address = null;

    #[ORM\Column(nullable: true)]
    private ?int $postal_code = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $city = null;

    #[ORM\OneToMany(mappedBy: 'school', targetEntity: Classroom::class)]
    private Collection $classrooms;

    public function __construct()
    {
        $this->classrooms = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?int
    {
        return $this->postal_code;
    }

    public function setPostalCode(?int $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return Collection<int, Classroom>
     */
    public function getClassrooms(): Collection
    {
        return $this->classrooms;
    }

    public function addClassroom(Classroom $classroom): self
    {
        if (!$this->classrooms->contains($classroom)) {
            $this->classrooms->add($classroom);
            $classroom->setSchool($this);
        }

        return $this;
    }

    public function removeClassroom(Classroom $classroom): self
    {
        if ($this->classrooms->removeElement($classroom)) {
            // set the owning side to null (unless already changed)
            if ($classroom->getSchool() === $this) {
                $classroom->setSchool(null);
            }
        }

        return $this;
    }
}

src/Form/SchoolType.php
<?php

namespace App\Form;

use App\Entity\School;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SchoolType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('address')
            ->add('postal_code')
            ->add('city')
            ->add('submit', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => School::class,
        ]);
    }
}

src/Controller/SchoolController.php
<?php

namespace App\Controller;


use App\Entity\School;
use App\Form\SchoolType;
use App\Repository\SchoolRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SchoolController extends AbstractController
{
    #[Route('/school', name: 'app_school')]
    public function index(SchoolRepository $schoolRepository): Response
    {

        $listSchool = $schoolRepository->findAll();

        return $this->render('school/index.html.twig', [
            'controller_name' => 'SchoolController',
            'listSchool' => $listSchool
        ]);
    }


    #[Route('/school/{id}', name: 'app_school_details')]
    public function details($id, SchoolRepository $schoolRepository): Response
    {
        $school = $schoolRepository->findOneById($id);

        return $this->render('school/details.html.twig', [
            'school' => $school
        ]);
    }

    #[Route('/schooladd', name: 'app_school_add')]
    public function add(Request $request, SchoolRepository $schoolRepository): Response
    {

        $school = new School();

        $form = $this->createForm(SchoolType::class, $school);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $schoolRepository->save($school, true);
            return $this->redirectToRoute('app_school');
        }

        return $this->render('school/add.html.twig', [
            'formAdd' => $form->createView()
        ]);
    }

    #[Route('/schooledit/{id}', name: 'app_school_edit')]
    public function edit($id, Request $request, SchoolRepository $schoolRepository): Response
    {

        $school = $schoolRepository->findOneById($id);

        $form = $this->createForm(SchoolType::class, $school);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $schoolRepository->save($school, true);
            return $this->redirectToRoute('app_school');
        }

        return $this->render('school/edit.html.twig', [
            'formEdit' => $form->createView()
        ]);
    }

    #[Route('/schoolremove/{id}', name: 'app_school_remove')]
    public function delete($id, SchoolRepository $schoolRepository): Response
    {
        $school = $schoolRepository->findOneById($id);
        $schoolRepository->remove($school, true);

        return $this->redirectToRoute('app_school');
    }
}

templates/school/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des écoles{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <a href="{{ path('app_school') }}"> <- Revenir aux écoles</a>
    <h1>Ajout d'une école</h1>

    {{ form(formAdd) }}
</div>
{% endblock %}

templates/school/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des écoles{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <a href="{{ path('app_school') }}"> <- Revenir aux écoles</a>
    <h1>Ecole {{school.name}}</h1>
    <p>
        {{school.address}}<br>
        {{school.postalCode}} {{school.city}}
    </p>
</div>
{% endblock %}

templates/school/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des écoles{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <a href="{{ path('app_school') }}"> <- Revenir aux écoles</a>
    <h1>Modification d'une école</h1>

    {{ form(formEdit) }}
</div>
{% endblock %}

templates/school/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des écoles{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Liste des écoles</h1>
    <a href="{{ path('app_school_add') }}">Ajouter une école</a>
    <table>
        <tr>
            <td>Nom</td>
            <td>Coordonnées</td>
            <td>Actions</td>
        </tr>

        {% for school in listSchool %}
        <tr>
            <td>{{school.name}}</td>
            <td>{{school.address}}</td>
            <td><a href="{{ path('app_school_details', {'id':school.id} )}}">Détail</a></td>
            <td><a href="{{ path('app_school_edit', {'id':school.id} )}}">Modification</a></td>
            <td><a href="{{ path('app_school_remove', {'id':school.id} )}}">Supprimer</a></td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}